name: EpicDuels
version: '${project.version}'
main: me.redyt008.epicduels.EpicDuels
api-version: '1.20'
author: Davide Razza
commands:
  duel:
    description: Inizia un duello con un Player!
    usage: /<command>
  daccept:
    description: Accetta una richiesta di duello
    usage: /<command>
  ddeny:
    description: Rifiuta una richiesta di duello
    usage: /<command>
  edtest:
    description: Comando di test
    usage: /<command>
  edstats:
    description: Comando per vedere le proprie statistiche
    usage: /<command>
  setrank:
    description: Comando per settarsi il rank
    usage: /<command>
  ranks:
    description: Guarda tutti i Rank esistenti
    usage: /<command>
  prearena:
    description: Imposta l'arena dove verranno tippati i player in duello
    usage: /<command>
  arena:
    description: Imposta l'arena dove verranno tippati i player in duello
    usage: /<command>
  stands:
    description: Imposta gli stand dove verranno tippati i player per spectare il duello
    usage: /<command>
  spect:
    description: Osserva un duello
    usage: /<command>
  epicduels:
    description: Comandi basici da amministratore
    usage: /<command>