name: EpicDuels
version: '${project.version}'
main: me.redyt008.epicduels.EpicDuels
api-version: '1.20'
commands:
  duel:
    description: Inizia un duello con un PLayer!
    usage: /<command>
  daccept:
    description: Accetta una richiesta di duello
    usage: /<command>
  ddeny:
    description: Rifiuta una richiesta di duello
    usage: /<command>
  edtest:
    description: Comando di test
    usage: /<command>
  edstats:
    description: Comando per vedere le proprie statistiche
    usage: /<command>
  setrank:
    description: Comando per settarsi il rank
    usage: /<command>
  ranks:
    description: Guarda tutti i Rank esistenti
    usage: /<command>